# Generated by Django 2.1.1 on 2018-10-03 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_todo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friendship',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
