# Generated by Django 2.1.1 on 2018-10-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('last_modified_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('membername', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'articles',
            },
        ),
        migrations.AlterField(
            model_name='msg',
            name='messageimage',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
