# Generated by Django 2.1.1 on 2018-10-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addfriend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myid', models.CharField(max_length=45)),
                ('askid', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'addfriend',
                'managed': True,
            },
        ),
    ]
