# Generated by Django 2.1.1 on 2018-10-11 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20181011_1111'),
        ('todo', '0003_members'),
    ]

    operations = [
    ]
