# Generated by Django 2.1.1 on 2018-10-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mem_name', models.CharField(max_length=45)),
                ('emailid', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=45)),
                ('gender', models.CharField(max_length=45)),
                ('company', models.CharField(max_length=60)),
                ('companyen', models.CharField(max_length=60)),
                ('position', models.CharField(max_length=60)),
                ('positionen', models.CharField(max_length=60)),
                ('skill', models.CharField(max_length=45)),
                ('language', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'members',
            },
        ),
    ]
