# Generated by Django 2.1.1 on 2018-09-22 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Articles',
        ),
        migrations.AlterModelTable(
            name='articles',
            table='articles',
        ),
    ]
