# Generated by Django 2.1.1 on 2018-09-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20180922_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='membername',
            field=models.CharField(default='IsTree', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articles',
            name='create_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='articles',
            name='last_modified_time',
            field=models.DateTimeField(),
        ),
    ]
